import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // Default rule for all crawlers
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
      },
      // Googlebot
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 1,
      },
      // Googlebot Image
      {
        userAgent: 'Googlebot-Image',
        allow: '/',
        crawlDelay: 1,
      },
      // Googlebot Video
      {
        userAgent: 'Googlebot-Video',
        allow: '/',
        crawlDelay: 1,
      },
      // Bingbot
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 2,
      },
      // Yahoo! Slurp
      {
        userAgent: 'Yahoo! Slurp',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 2,
      },
      // Yandex
      {
        userAgent: 'Yandex',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 3,
      },
      // Yandex Images
      {
        userAgent: 'YandexImages',
        allow: '/',
        crawlDelay: 3,
      },
      // DuckDuckBot
      {
        userAgent: 'DuckDuckBot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 2,
      },
      // Baiduspider (Chinese search engine)
      {
        userAgent: 'Baiduspider',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 5,
      },
      // Sogou (Chinese search engine)
      {
        userAgent: 'Sogou',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 3,
      },
      // Exabot (French search engine)
      {
        userAgent: 'Exabot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 3,
      },
      // Facebook Crawler
      {
        userAgent: 'facebookexternalhit',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 1,
      },
      // Twitterbot
      {
        userAgent: 'Twitterbot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 1,
      },
      // LinkedIn Bot
      {
        userAgent: 'LinkedInBot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 2,
      },
      // Pinterest Bot
      {
        userAgent: 'Pinterestbot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 2,
      },
      // WhatsApp Bot
      {
        userAgent: 'WhatsApp',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 1,
      },
      // AppleBot (Siri/Safari)
      {
        userAgent: 'AppleBot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 2,
      },
      // SemrushBot (SEO tool)
      {
        userAgent: 'SemrushBot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 5,
      },
      // AhrefsBot (SEO tool)
      {
        userAgent: 'AhrefsBot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 5,
      },
      // MJ12bot (Majestic SEO)
      {
        userAgent: 'MJ12bot',
        allow: '/',
        disallow: [
          '/cart',
          '/checkout',
          '/orders',
          '/login',
          '/register',
          '/account',
          '/wishlist',
          '/compare',
          '/api/',
          '/_next/',
          '/admin/',
          '/dashboard/',
          '/profile/',
          '/settings/',
        ],
        crawlDelay: 5,
      },
    ],
    sitemap: 'https://www.topthreadz.com.pk/sitemap.xml',
    host: 'https://www.topthreadz.com.pk',
  };
}